version: "3.2"

services:
    web_api:
        build: .
        image: felixt/gerrymandering_viz/web_api:dev
        container_name: gerrymandering_viz-web_api
        volumes:
            - type: bind
              source: .
              target: /home
        ports:
            - "${PORT_DEV}"
        stdin_open: true
        tty: true
        entrypoint: /bin/bash
        environment:
            ENV: DEV
