version: "3.2"

services:
    data_wrangler:
        image: felixt/gerrymandering_viz/data_wrangler
        container_name: gerrymandering_viz-data_wrangler
        build: .
        volumes:
            - type: bind
              source: .
              target: /home
        stdin_open: true
        tty: true
        entrypoint: /bin/bash
