version: "3.2"

services:
    data_wrangler:
        image: felixt/gerrymandering_viz/data_wrangler:dev
        container_name: gerrymandering_viz-data_wrangler
        build: .
        volumes:
            - type: bind
              source: .
              target: /home
        stdin_open: true
        tty: true
        entrypoint: /bin/bash
        links:
            - postgres

    postgres:
        image: postgres:9.6-alpine
        container_name: gerrymandering_viz-db_dev
        environment:
            - POSTGRES_DB=${DB_NAME_DEV}
            - POSTGRES_USER=${DB_USER_DEV}
            - POSTGRES_PASSWORD=${DB_PASSWORD_DEV}
            - PGDATA=${PGDATA_DEV}
        ports:
            - 5432:5432
