# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictElectionResult',
            fields=[
                ('district_election_results_id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField()),
                ('votes_dem', models.PositiveIntegerField()),
                ('votes_rep', models.PositiveIntegerField()),
                ('votes_other', models.PositiveIntegerField()),
                ('votes_total', models.PositiveIntegerField()),
                ('votes_wasted_dem', models.PositiveIntegerField()),
                ('votes_wasted_rep', models.PositiveIntegerField()),
                ('votes_wasted_net', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'district_election_results',
            },
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('election_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=2)),
                ('year', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'elections',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_id', models.AutoField(primary_key=True, serialize=False)),
                ('iso_a2', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=14)),
            ],
            options={
                'db_table': 'states',
            },
        ),
        migrations.CreateModel(
            name='StateElectionResult',
            fields=[
                ('election', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Election')),
                ('votes_dem', models.PositiveIntegerField()),
                ('votes_rep', models.PositiveIntegerField()),
                ('votes_other', models.PositiveIntegerField()),
                ('votes_total', models.PositiveIntegerField()),
                ('votes_wasted_dem', models.PositiveIntegerField()),
                ('votes_wasted_rep', models.PositiveIntegerField()),
                ('votes_wasted_net', models.PositiveIntegerField()),
                ('efficiency_gap', models.DecimalField(decimal_places=3, max_digits=4)),
            ],
            options={
                'db_table': 'state_election_results',
            },
        ),
        migrations.AddField(
            model_name='districtelectionresult',
            name='election_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Election'),
        ),
    ]
